-- PALF EMERGENCY PERMISSION FIX
-- This script safely creates all tables and fixes the admin permission system

-- 1. Create Core Tables (If they don't exist)

-- Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'staff' CHECK (role IN ('admin', 'staff')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- News
CREATE TABLE IF NOT EXISTS public.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT,
  published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  author TEXT DEFAULT 'Pan Afric Law Firm'
);

-- Insights
CREATE TABLE IF NOT EXISTS public.insights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT,
  published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  author TEXT DEFAULT 'Pan Afric Law Firm'
);

-- Site Config
CREATE TABLE IF NOT EXISTS public.site_config (
  id TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  category TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_config ENABLE ROW LEVEL SECURITY;

-- 3. Create Admin Check Function (Security Definer)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Clean up old policies
DROP POLICY IF EXISTS "Admins manage news" ON news;
DROP POLICY IF EXISTS "Admins manage insights" ON insights;
DROP POLICY IF EXISTS "Admins manage config" ON site_config;
DROP POLICY IF EXISTS "Admins manage profiles" ON profiles;
DROP POLICY IF EXISTS "Admins can manage all profiles" ON profiles;
DROP POLICY IF EXISTS "Public News Access" ON news;
DROP POLICY IF EXISTS "Public Insights Access" ON insights;
DROP POLICY IF EXISTS "Public Config Access" ON site_config;
DROP POLICY IF EXISTS "Users can view own profile" ON profiles;

-- 5. Set up new robust policies

-- Public Read Access
CREATE POLICY "Public News Access" ON news FOR SELECT USING (true);
CREATE POLICY "Public Insights Access" ON insights FOR SELECT USING (true);
CREATE POLICY "Public Config Access" ON site_config FOR SELECT USING (true);
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);

-- Admin Full Access
CREATE POLICY "Admins manage news" ON news FOR ALL USING (is_admin());
CREATE POLICY "Admins manage insights" ON insights FOR ALL USING (is_admin());
CREATE POLICY "Admins manage config" ON site_config FOR ALL USING (is_admin());
CREATE POLICY "Admins manage profiles" ON profiles FOR ALL USING (is_admin());

-- 6. Permissions
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated, anon;
