-- 1. Profiles Table (For Admin Authorization)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'staff' CHECK (role IN ('admin', 'staff')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Admins can manage all profiles
CREATE POLICY "Admins can manage all profiles" ON profiles
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Users can view their own profile
CREATE POLICY "Users can view own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);

-- 2. Consultations Table (For Inquiry Forms)
CREATE TABLE IF NOT EXISTS consultations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'pending' -- 'pending', 'reviewed', 'contacted'
);

-- Enable RLS
ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;

-- Allow anyone to submit a consultation inquiry (Public Insert)
CREATE POLICY "Enable insert for everyone" ON consultations
  FOR INSERT WITH CHECK (true);

-- Only authenticated admins can view inquiries (To be set up later)
-- CREATE POLICY "Admins can view consultations" ON consultations
--   FOR SELECT USING (auth.role() = 'authenticated');

-- 2. Newsletter Table (Optional, for future use)
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for anonymous" ON newsletter_subscribers
  FOR INSERT WITH CHECK (true);

-- 3. News Table (For Dynamic News Updates)
CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  category TEXT NOT NULL, -- e.g., 'Firm News', 'Legal Alerts', 'Press Release'
  image_url TEXT,
  published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  author TEXT DEFAULT 'Pan Afric Law Firm'
);

ALTER TABLE news ENABLE ROW LEVEL SECURITY;

-- Allow public read access to News
CREATE POLICY "Public News Access" ON news
  FOR SELECT USING (true);

-- Admins can manage news
CREATE POLICY "Admins manage news" ON news
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- 4. Insights Table (For Expert Legal Analysis)
CREATE TABLE IF NOT EXISTS insights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  category TEXT NOT NULL, -- e.g., 'Ethiopian Legal', 'Regulatory', 'Investment'
  image_url TEXT,
  published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  author TEXT DEFAULT 'Pan Afric Law Firm'
);

ALTER TABLE insights ENABLE ROW LEVEL SECURITY;

-- Allow public read access to Insights
CREATE POLICY "Public Insights Access" ON insights
  FOR SELECT USING (true);

-- Admins can manage insights
CREATE POLICY "Admins manage insights" ON insights
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- 5. Site Config Table (Dynamic Button/Text Control)
CREATE TABLE IF NOT EXISTS site_config (
  id TEXT PRIMARY KEY, -- e.g., 'home_hero_title'
  value JSONB NOT NULL,
  category TEXT NOT NULL, -- e.g., 'home', 'navbar', 'contact'
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE site_config ENABLE ROW LEVEL SECURITY;

-- Public can read config
CREATE POLICY "Public Config Access" ON site_config
  FOR SELECT USING (true);

-- Admins can edit config
CREATE POLICY "Admins manage config" ON site_config
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );
