-- Create the consultations table for inquiry forms
CREATE TABLE IF NOT EXISTS consultations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'pending' -- 'pending', 'reviewed', 'contacted'
);

-- Enable Row Level Security
ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;

-- Allow public insertion
DROP POLICY IF EXISTS "Enable insert for everyone" ON consultations;
CREATE POLICY "Enable insert for everyone" ON consultations FOR INSERT WITH CHECK (true);

-- Allow admins to view and manage
DROP POLICY IF EXISTS "Admins can manage consultations" ON consultations;
CREATE POLICY "Admins can manage consultations" ON consultations
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'staff')
    )
  );
