-- Create the network applications table for legal professional join requests
CREATE TABLE IF NOT EXISTS network_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  full_name TEXT NOT NULL,
  firm_name TEXT,
  email TEXT NOT NULL,
  phone TEXT,
  location TEXT NOT NULL,
  practice_areas TEXT[], -- Array of practice areas
  experience_years INTEGER,
  message TEXT,
  profile_image_url TEXT, -- URL for the uploaded profile picture
  status TEXT DEFAULT 'pending' -- 'pending', 'approved', 'rejected'
);

-- Enable Row Level Security
ALTER TABLE network_applications ENABLE ROW LEVEL SECURITY;

-- 1. Allow anyone to submit an application (Public Insert)
DROP POLICY IF EXISTS "Enable insert for public" ON network_applications;
CREATE POLICY "Enable insert for public" ON network_applications
  FOR INSERT WITH CHECK (true);

-- 2. Allow authenticated users (Admins/Staff) to view and manage applications
DROP POLICY IF EXISTS "Admins can manage network applications" ON network_applications;
CREATE POLICY "Admins can manage network applications" ON network_applications
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role IN ('admin', 'staff')
    )
  );
