"use client";

import { useState, useEffect } from "react";
import { supabase } from "@/lib/supabase-client";
import { 
    Zap, 
    RefreshCw, 
    CheckCircle2, 
    AlertCircle, 
    Clock, 
    ExternalLink, 
    Edit2, 
    Trash2 
} from "lucide-react";
import Link from "next/link";

export default function AiEnginePortal() {
    const [loading, setLoading] = useState(false);
    const [history, setHistory] = useState<any[]>([]);
    const [status, setStatus] = useState<{ type: 'success' | 'error', text: string } | null>(null);

    useEffect(() => {
        fetchAiHistory();
    }, []);

    async function fetchAiHistory() {
        // Fetch recent items generated by AI
        const [news, insights, events, ventures] = await Promise.all([
            supabase.from('news').select('*').eq('author', 'Pan Afric Law Firm Content Engine').order('created_at', { ascending: false }).limit(3),
            supabase.from('insights').select('*').eq('author', 'Pan Afric Editorial Team').order('created_at', { ascending: false }).limit(3),
            supabase.from('career_events').select('*').order('created_at', { ascending: false }).limit(3), // Events don't have author yet, so we'll just take recent
            supabase.from('networking_ventures').select('*').order('created_at', { ascending: false }).limit(3)
        ]);

        const combined = [
            ...(news.data || []).map(i => ({ ...i, type: 'News' })),
            ...(insights.data || []).map(i => ({ ...i, type: 'Insight' })),
            ...(events.data || []).map(i => ({ ...i, type: 'Event' })),
            ...(ventures.data || []).map(i => ({ ...i, type: 'Venture' }))
        ].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

        setHistory(combined.slice(0, 10));
    }

    async function handleGenerateBatch() {
        if (!confirm("This will trigger Gemini to generate one new item for every category (4 total). Continue?")) return;
        
        setLoading(true);
        setStatus(null);
        try {
            const res = await fetch('/api/admin/auto-generate', { 
                method: 'POST',
                headers: {
                    'Authorization': `Bearer palf_content_engine_secret_2026` // Using the local secret
                }
            });
            
            if (!res.ok) throw new Error("Generation failed");
            
            const data = await res.json();
            setStatus({ type: 'success', text: "Success! AI generated: " + Object.values(data.added).join(", ") });
            fetchAiHistory();
        } catch (err: any) {
            setStatus({ type: 'error', text: "AI Error: " + err.message });
        } finally {
            setLoading(false);
        }
    }

    return (
        <div className="space-y-12 max-w-6xl">
            {/* Header / Stats */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div className="bg-white border border-border p-8 rounded-sm shadow-sm space-y-4">
                    <div className="h-10 w-10 bg-secondary/10 rounded-full flex items-center justify-center text-secondary">
                        <Zap size={20} />
                    </div>
                    <div>
                        <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-muted">A.I. Status</h3>
                        <p className="font-serif text-xl font-black italic">Active & Ready</p>
                    </div>
                </div>
                <div className="bg-white border border-border p-8 rounded-sm shadow-sm space-y-4">
                    <div className="h-10 w-10 bg-emerald-50 rounded-full flex items-center justify-center text-emerald-500">
                        <Clock size={20} />
                    </div>
                    <div>
                        <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-muted">Daily Schedule</h3>
                        <p className="font-serif text-xl font-black italic">06:00 UTC</p>
                    </div>
                </div>
                <div className="flex items-center justify-end">
                    <button
                        onClick={handleGenerateBatch}
                        disabled={loading}
                        className="bg-black text-white px-10 py-5 rounded-sm font-sans font-bold uppercase tracking-widest text-xs hover:bg-secondary transition-all flex items-center space-x-3 shadow-2xl disabled:opacity-50"
                    >
                        {loading ? <RefreshCw className="animate-spin" size={18} /> : <Zap size={18} />}
                        <span>Trigger Full Content Cycle</span>
                    </button>
                </div>
            </div>

            {/* Notifications */}
            {status && (
                <div className={`p-6 rounded-sm border-l-4 flex items-center space-x-4 animate-in fade-in slide-in-from-top-4 ${
                    status.type === 'success' ? 'bg-emerald-50 border-emerald-500 text-emerald-800' : 'bg-red-50 border-red-500 text-red-800'
                }`}>
                    {status.type === 'success' ? <CheckCircle2 size={24} /> : <AlertCircle size={24} />}
                    <p className="text-sm font-medium">{status.text}</p>
                </div>
            )}

            {/* AI History Table */}
            <div className="bg-white border border-border rounded-sm shadow-sm overflow-hidden">
                <div className="p-8 border-b border-border bg-[#fcfcfc]">
                    <h2 className="font-serif text-2xl font-black italic">Recent AI Creations</h2>
                    <p className="text-xs text-muted font-sans font-light mt-2 uppercase tracking-widest">A review of the last 10 items generated by the Content Engine</p>
                </div>
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="border-b border-border bg-[#fafafa]">
                            <th className="px-8 py-5 text-[10px] font-black uppercase tracking-widest text-muted">Type</th>
                            <th className="px-8 py-5 text-[10px] font-black uppercase tracking-widest text-muted">Generated Title</th>
                            <th className="px-8 py-5 text-[10px] font-black uppercase tracking-widest text-muted">Status</th>
                            <th className="px-8 py-5 text-[10px] font-black uppercase tracking-widest text-muted text-right">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {history.length === 0 ? (
                            <tr>
                                <td colSpan={4} className="px-8 py-20 text-center text-muted italic font-sans text-sm">
                                    No AI-generated history found yet.
                                </td>
                            </tr>
                        ) : (
                            history.map((item) => (
                                <tr key={item.id} className="border-b border-border hover:bg-gray-50 transition-colors group">
                                    <td className="px-8 py-6 font-sans text-[10px] font-black uppercase tracking-[0.1em] text-secondary">
                                        {item.type}
                                    </td>
                                    <td className="px-8 py-6">
                                        <p className="text-sm font-bold text-black group-hover:text-secondary transition-colors">{item.title}</p>
                                        <p className="text-[10px] text-muted tracking-tight">{new Date(item.created_at).toLocaleString()}</p>
                                    </td>
                                    <td className="px-8 py-6">
                                        <span className="bg-emerald-50 text-emerald-600 px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest">Live</span>
                                    </td>
                                    <td className="px-8 py-6 text-right">
                                        <div className="flex items-center justify-end space-x-3">
                                            <Link 
                                                href={`/admin/${item.type.toLowerCase() === 'event' ? 'careers/events' : item.type.toLowerCase() === 'venture' ? 'careers/ventures' : item.type.toLowerCase() + '/' + (item.id)}`}
                                                className="p-2 text-muted hover:text-black transition-colors"
                                            >
                                                <Edit2 size={16} />
                                            </Link>
                                            <button className="p-2 text-muted hover:text-red-500 transition-colors">
                                                <Trash2 size={16} />
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>

            {/* AI Control Panel */}
            <div className="bg-black text-white p-12 rounded-sm shadow-2xl relative overflow-hidden group">
                <div className="relative z-10 space-y-6 max-w-2xl">
                    <h2 className="font-serif text-3xl font-black italic text-secondary">A.I. Engine Configuration</h2>
                    <p className="text-white/60 font-sans font-light leading-relaxed">
                        The content engine is currently using <span className="text-white font-bold">Llama 3.1 8B (via Groq)</span>. 
                        To pause the daily morning uploads, you must disable the <span className="text-secondary italic">"Daily Content Generation"</span> workflow in your GitHub Repository settings.
                    </p>
                    <div className="pt-4 flex space-x-4">
                        <div className="bg-white/5 border border-white/10 p-4 rounded-sm flex-1">
                            <p className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-1">Model Version</p>
                            <p className="font-sans text-sm font-bold">llama-3.1-8b-instant</p>
                        </div>
                        <div className="bg-white/5 border border-white/10 p-4 rounded-sm flex-1">
                            <p className="text-[10px] font-black uppercase tracking-widest text-white/40 mb-1">Authorization</p>
                            <p className="font-sans text-sm font-bold">Bearer ...2026</p>
                        </div>
                    </div>
                </div>
                <Zap className="absolute -right-20 -bottom-20 h-80 w-80 text-white/5 rotate-12 group-hover:rotate-0 transition-transform duration-1000" />
            </div>
        </div>
    );
}
